# Generated by Django 4.1.6 on 2023-04-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_currency_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="flag",
        ),
    ]
