# Generated by Django 4.2 on 2023-05-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_country_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="smaller_unit",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
