# Generated by Django 4.1.3 on 2022-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
