# Generated by Django 4.1.3 on 2022-11-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_customeraddress_street_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
