# Generated by Django 4.1.3 on 2022-11-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_alter_product_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAddress',
            new_name='Address',
        ),
    ]
