# Generated by Django 4.1.3 on 2022-11-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.transport'),
        ),
    ]
