# Generated by Django 4.1.3 on 2022-11-25 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_alter_invoice_terms_alter_stock_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoicing.invoice')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('packing_charges', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveBigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiceitems', to='invoicing.product')),
            ],
        ),
        migrations.DeleteModel(
            name='InvoiceProduct',
        ),
    ]
