# Generated by Django 4.1.3 on 2022-11-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_invoiceitem_delete_invoiceproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'product')},
        ),
    ]
