# Generated by Django 4.1.3 on 2022-12-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_remove_address_id_alter_address_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='firm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoicing.firm'),
            preserve_default=False,
        ),
    ]
