# Generated by Django 4.1.3 on 2022-12-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_invoice_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(default='URP', max_length=55),
            preserve_default=False,
        ),
    ]
