# Generated by Django 4.1.3 on 2022-12-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_customer_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='gstin',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
