# Generated by Django 4.1.3 on 2022-11-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_alter_invoiceitem_invoice_alter_invoiceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitems', to='invoicing.invoice'),
        ),
    ]
