# Generated by Django 4.1.3 on 2022-11-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_invoiceitem_id_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
