# Generated by Django 4.1.4 on 2022-12-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_firm_gstin_alter_customer_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmLogo',
            fields=[
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='logo', serialize=False, to='invoicing.firm')),
                ('image', models.ImageField(upload_to='store/images')),
            ],
        ),
    ]
