# Generated by Django 4.1.4 on 2022-12-22 08:17

from django.db import migrations, models
import invoicing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_firmlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmlogo',
            name='image',
            field=models.ImageField(upload_to='invoicing/images', validators=[invoicing.validators.validate_file_size]),
        ),
    ]
