# Generated by Django 4.1.3 on 2022-11-25 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_delete_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('packing_charges', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveBigIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitems', to='invoicing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='invoicing.product')),
            ],
            options={
                'unique_together': {('invoice', 'product')},
            },
        ),
    ]
