# Generated by Django 4.1.6 on 2023-02-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0014_alter_firmlogo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hsn",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
