# Generated by Django 4.1.3 on 2022-11-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_alter_invoiceitem_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
