# Generated by Django 4.1.6 on 2023-02-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0016_bank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="id",
        ),
        migrations.RemoveField(
            model_name="bank",
            name="user",
        ),
        migrations.AddField(
            model_name="bank",
            name="firm",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="invoicing.firm",
            ),
            preserve_default=False,
        ),
    ]
