# Generated by Django 4.1.3 on 2022-11-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_remove_invoice_tax_remove_invoice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='transport',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoicing.invoice'),
        ),
    ]
