# Generated by Django 4.1.6 on 2023-02-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0017_remove_bank_id_remove_bank_user_bank_firm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="transport",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoicing.transport",
            ),
        ),
    ]
