# Generated by Django 4.1.6 on 2023-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0018_alter_invoice_transport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="transporter_id",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
