# Generated by Django 4.1.3 on 2022-11-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0018_transport_id_alter_transport_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
