# Generated by Django 4.1.6 on 2023-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0019_alter_transport_transporter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="branch",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name="bank",
            name="ifsc",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
