# Generated by Django 4.1.3 on 2022-11-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoicing.transport'),
            preserve_default=False,
        ),
    ]
