# Generated by Django 4.1.6 on 2023-04-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("invoicing", "0020_alter_bank_branch_alter_bank_ifsc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="country",
        ),
        migrations.AddField(
            model_name="customer",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
