# Generated by Django 4.1.6 on 2023-04-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_country_flag"),
        ("invoicing", "0021_remove_customer_country_customer_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="object_id",
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.country",
            ),
            preserve_default=False,
        ),
    ]
