# Generated by Django 4.1.3 on 2022-11-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_remove_transport_invoice_invoice_transport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
    ]
