# Generated by Django 4.1.6 on 2023-04-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0022_remove_customer_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="transport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoicing.transport",
            ),
        ),
    ]
