# Generated by Django 4.1.3 on 2022-11-27 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0022_alter_invoiceitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='packing_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
