# Generated by Django 4.1.6 on 2023-04-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_country_flag"),
        ("invoicing", "0023_alter_invoice_transport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.country"
            ),
        ),
    ]
