# Generated by Django 4.1.6 on 2023-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0024_alter_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
