# Generated by Django 4.1.6 on 2023-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0025_transport_vehicle_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="ewaybill",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="order_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
