# Generated by Django 4.1.6 on 2023-04-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0026_invoice_ewaybill_invoice_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="datetime",
            field=models.DateField(auto_now=True),
        ),
    ]
