# Generated by Django 4.1.6 on 2023-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0027_alter_payment_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="datetime",
            field=models.DateField(),
        ),
    ]
