# Generated by Django 4.2 on 2023-05-01 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0028_alter_payment_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="transportation_charges",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
